Importação das bibliotecas necessárias

In [7]:
import json
import requests
import pandas as pd
from dataclasses import dataclass

Coleta de dados da API REST

In [6]:
r = requests.get("http://127.0.0.1:5000/country")
data = r.json()

linhas = []
for codigo, info in data.items():
    linhas.append({
        "codigo" : codigo,
        "nome" : info["name"],
        "codigo_moeda" : info["currency"],
        "populacao" : info ["population"],
        "capital" : info["capital"],
        "area" : info["area"]
    })

    df = pd.DataFrame(linhas)
    print(df.head())

    df.to_csv("paises_api.csv", index=False)

  codigo     nome codigo_moeda  populacao           capital   area
0    AND  Andorra          EUR      77006  Andorra la Vella  468.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi

      area
0    468.0
1  82880.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul

       area
0     468.0
1   82880.0
2  647500.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul
3    ATG   Antigua and Barbuda          XCD      96286         St John's
4    AIA              Anguilla          XCD      13254        The Valley

       area
0     468.0
1   82880.0
2  647500.0
3     443.0
4     102.0
  codigo                  nome codigo_moeda  populacao           capital  \
0    AND               Andorra          EUR      77006  Andorra la Vella
1    ARE  United Arab Emirates          AED    9630959         Abu Dhabi
2    AFG           Afghanistan          AFN   37172386             Kabul

Leitura do arquivo CSV gdp_data

In [10]:
df = pd.read_csv('./gdp_data.csv',sep=',')
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129081e+10,2.180870e+10,2.370727e+10,2.821034e+10,2.611906e+10,2.968249e+10,...,9.834729e+11,1.003768e+12,9.245228e+11,8.827213e+11,1.021119e+12,1.007240e+12,1.001017e+12,9.274845e+11,1.080712e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,8.322169e+11,8.924979e+11,7.669580e+11,6.905454e+11,6.837480e+11,7.663597e+11,7.947191e+11,7.847997e+11,8.401873e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.361907e+10,6.740429e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10,NaN

    Leitura dos arquivos CSV paises_api (obtido por meio da API REST) e gdp_data com dados complementares sobre o PIB dos países entre 1960 a 2022

In [11]:
paises = pd.read_csv('paises_api.csv')
gdp = pd.read_csv('gdp_data.csv')

Seleção da coluna PIB

In [12]:
colunas_gdp = ['Country Code'] + [str(ano) for ano in range(1960, 2022)]
gdp = gdp[colunas_gdp]

Inserir o mesmo índice nas duas tabelas (código do país)

In [13]:
paises = paises.set_index('codigo')          # coluna do paises_api
gdp = gdp.set_index('Country Code')         # coluna do gdp_data

Concatenação dos dados em um único dataframe

In [14]:
df_final = pd.concat([paises, gdp], axis=1)

Salvar em CSV

In [15]:
df_final.to_csv('paises_api_com_pib_concat.csv', index=False)

Visualização da planilha com os dados concatenados

In [16]:
df_final

,nome,codigo_moeda,populacao,capital,area,1960,1961,1962,1963,1964,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
AND,Andorra,EUR,77006.0,Andorra la Vella,468.0,NaN,NaN,NaN,NaN,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
ARE,United Arab Emirates,AED,9630959.0,Abu Dhabi,82880.0,NaN,NaN,NaN,NaN,NaN,...,3.846101e+11,4.002185e+11,4.141054e+11,3.702755e+11,3.692553e+11,3.905168e+11,4.270494e+11,4.179897e+11,3.494730e+11,4.150216e+11
AFG,Afghanistan,AFN,37172386.0,Kabul,647500.0,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
ATG,Antigua and Barbuda,XCD,96286.0,St John's,443.0,NaN,NaN,NaN,NaN,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
AIA,Anguilla,XCD,13254.0,The Valley,102.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TMN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.743926e+12,1.601617e+12,1.586867e+12,1.425099e+12,1.460439e+12,1.448152e+12,1.374528e+12,1.376677e+12,1.257616e+12,1.472403e+12
TSA,NaN,NaN,NaN,NaN,NaN,4.715671e+10,5.031685e+10,5.370559e+10,6.040834e+10,6.915898e+10,...,2.302399e+12,2.362710e+12,2.587789e+12,2.704836e+12,3.010758e+12,3.433882e+12,3.534209e+12,3.653951e+12,3.487013e+12,4.088771e+12
TSS,NaN,NaN,NaN,NaN,NaN,3.116738e+10,3.242300e+10,3.508183e+10,4.010602e+10,3.937704e+10,...,1.708394e+12,1.815690e+12,1.896266e+12,1.691481e+12,1.573267e+12,1.704867e+12,1.773600e+12,1.795736e+12,1.712284e+12,1.920899e+12
UMC,NaN,NaN,NaN,NaN,NaN,2.419478e+11,2.183622e+11,2.239607e+11,2.349677e+11,2.696465e+11,...,1.891479e+13,2.030664e+13,2.093960e+13,1.966354e+13,1.954982e+13,2.164484e+13,2.330450e+13,2.368174e+13,2.285137e+13,2.710409e+13
WLD,NaN,NaN,NaN,NaN,NaN,1.392277e+12,1.448625e+12,1.550548e+12,1.671614e+12,1.830292e+12,...,7.550115e+13,7.760719e+13,7.973315e+13,7.518784e+13,7.646155e+13,8.140067e+13,8.645689e+13,8.764526e+13,8.510560e+13,9.651308e+13